-- 코드를 입력하세요
SELECT DISTINCT ICECREAM_INFO.FLAVOR 
FROM FIRST_HALF JOIN ICECREAM_INFO
WHERE ICECREAM_INFO.FLAVOR  = FIRST_HALF.FLAVOR AND
FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
