-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%k') AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE  DATE_FORMAT(DATETIME, '%k') BETWEEN 9 AND 19
GROUP BY  DATE_FORMAT(DATETIME, '%k')
ORDER BY  DATE_FORMAT(DATETIME, '%k')*1